gxt -g VC -i "american.txt" -o "../../gamefiles/TEXT/american.gxt"
gxt -g VC -i "french.txt" -o "../../gamefiles/TEXT/french.gxt"
gxt -g VC -i "german.txt" -o "../../gamefiles/TEXT/german.gxt"
gxt -g VC -i "italian.txt" -o "../../gamefiles/TEXT/italian.gxt"
gxt -g VC -i "spanish.txt" -o "../../gamefiles/TEXT/spanish.gxt"